name: blalala

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    blabla:
        name: Testing

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.14.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3